# Import Libraries

In [1]:
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

# Load Dataset

In [2]:
iris = load_iris()

X = iris.data
y = iris.target

# Display Dataset

In [3]:
df = pd.DataFrame(X, columns=iris.feature_names)

df['Species'] = y

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

# Split Dataset

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Logistic Regression

In [5]:
lr = LogisticRegression(max_iter=200)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

# Decision Tree

In [6]:
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

# KNN

In [7]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

# SVM

In [8]:
svm = SVC(kernel='linear')

svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

# Compare All Models

In [9]:
results = pd.DataFrame({

'Algorithm':[
'Logistic Regression',
'Decision Tree',
'KNN',
'SVM'
],

'Accuracy':[

accuracy_score(y_test, lr_pred),
accuracy_score(y_test, dt_pred),
accuracy_score(y_test, knn_pred),
accuracy_score(y_test, svm_pred)

],

'Precision':[

precision_score(y_test, lr_pred, average='weighted'),
precision_score(y_test, dt_pred, average='weighted'),
precision_score(y_test, knn_pred, average='weighted'),
precision_score(y_test, svm_pred, average='weighted')

],

'Recall':[

recall_score(y_test, lr_pred, average='weighted'),
recall_score(y_test, dt_pred, average='weighted'),
recall_score(y_test, knn_pred, average='weighted'),
recall_score(y_test, svm_pred, average='weighted')

],

'F1 Score':[

f1_score(y_test, lr_pred, average='weighted'),
f1_score(y_test, dt_pred, average='weighted'),
f1_score(y_test, knn_pred, average='weighted'),
f1_score(y_test, svm_pred, average='weighted')

]

})

results

             Algorithm  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression       1.0        1.0     1.0       1.0
1        Decision Tree       1.0        1.0     1.0       1.0
2                  KNN       1.0        1.0     1.0       1.0
3                  SVM       1.0        1.0     1.0       1.0

# Best Model

In [10]:
best_model = results.sort_values(
    by='Accuracy',
    ascending=False
)

best_model

             Algorithm  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression       1.0        1.0     1.0       1.0
1        Decision Tree       1.0        1.0     1.0       1.0
2                  KNN       1.0        1.0     1.0       1.0
3                  SVM       1.0        1.0     1.0       1.0